services:
  lookingpromos.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - MongoDbConnectionOptions__ConnectionString=${DATABASE_URI}
      - MongoDbConnectionOptions__DatabaseName=${DATABASE_INSTANCE}
      - MessageBrokerOptions__Username=${RABBITMQ_USER}
      - MessageBrokerOptions__Password=${RABBITMQ_PASSWORD}
      - MessageBrokerOptions__ConnectionString=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672
    ports:
      - "5001:80"
      - "5000:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  lookingpromos.worker:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - MongoDbConnectionOptions__ConnectionString=${DATABASE_URI}
      - MongoDbConnectionOptions__DatabaseName=${DATABASE_INSTANCE}
      - MessageBrokerOptions__Username=${RABBITMQ_USER}
      - MessageBrokerOptions__Password=${RABBITMQ_PASSWORD}
      - MessageBrokerOptions__ConnectionString=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
